### ISSUE TITLE
pm2の動きについて文書化されていない

### ISSUE THREAD

**Issue by h-takeyeah** [su-its/ams-backend#40]
pm2の挙動について特に 👉 https://github.com/su-its/ams-backend-nodejs/issues/15#issuecomment-791864073 のようなログ周りの機能が周知できていなかったと感じました．

そこでpm2が何をしているのか，特にログについて説明する文章を書く必要があると思います． @Stroheim001 の指摘(https://github.com/su-its/ams-backend-nodejs/pull/38#issuecomment-792282119) のとおりdocsからアクセスできる場所に書きたいと思います．とりあえずサンプル的なものを作ってぶら下げます．

**Comment by h-takeyeah** [comment]
f7af8f3e1ac512aaf680e00e0ace1001acef8fc4 で解決

**Comment by h-takeyeah** [comment]
ありがとうございました

**Comment by equal-l2** [comment]
本当に解決しましたか？
stkさんの意図は「ログファイル等がどこに出るのか」、というか「そもそもログが保存されるのか」とかのレベルだったと思うのですが

**Comment by Stroheim001** [comment]
@equal-l2 @h-takeyeah このタイトルだと解消された感ありますが、

私が一番最初に行ってたのはログが出てますか？なので、青シャツさんの指摘の通りです。

ただ、このissueがドキュメントを修正するだけというスコープなら閉じるべきだと思います。

どうするかはお任せします。

**Comment by h-takeyeah** [comment]
そうですね．すみません早計でした．ログファイルの形について書いてみます．

**Comment by Stroheim001** [comment]
@h-takeyeah まだエラーハンドリングの段階にないと思いますが、このエラーが出たときはこう対処してほしい的なのがあると

とてもドキュメントとして優れていると思います。また、それを通して部分的な理解から全体像をつかむ糸口になるかもしれません

**Comment by equal-l2** [comment]
@h-takeyeah この件、その後どうですか？

**Comment by h-takeyeah** [comment]
@equal-l2 deploayment.mdに書いた以上の作業はしていません(つまり「わかる人が見たらわかるけど全くわからない人が見て何とかできる内容にはなっていない」と指摘されたときのままです)

**Comment by h-takeyeah** [comment]
この作業は完全に後回しにしていました．今クイックスタートガイドをおよそ書き終えたので取り掛かります．
