### ISSUE TITLE
CI: Redpenから出力されるResult.txtをPRに表示する

### ISSUE THREAD

**Issue by equal-l2** [su-its/ams-backend#47]
この辺を使ってPRにコメントとして表示したい
https://github.com/actions/github-script

**Comment by equal-l2** [comment]
javaを使うならこのactionでセットアップすることができます
(自分でaptを使わないでセットアップできる)
https://github.com/actions/setup-java

あとreviewdog経由でredpenを使うこともできます
(スター0なので怪しい……)
https://github.com/tsuyoshicho/action-redpen

**Comment by Stroheim001** [comment]
@equal-l2 めっちゃこれ探してました。

割と近いところまで行ってたので、感謝です。

後、localのDockerのRedpenも高速化しました。

さらに使い方も追記しておいたので、これ直したらかなりCIが便利になると思います。

**Comment by Stroheim001** [comment]
@equal-l2 今日はこれに対応したいと思います。すでにいくつか実験してます。

**Comment by equal-l2** [comment]
#85 で完了
