### ISSUE TITLE
入退室のエンドポイントをrdr-brdge以外も叩けてしまう問題

### ISSUE THREAD

**Issue by h-takeyeah** [su-its/ams-backend#65]
現状では入退室のエンドポイントである`/room`をrdr-bridge以外のクライアントも~~叩けるし~~リクエストを飛ばせるしそれでSQLが走ってしまう．rdr-bridge以外が~~叩けてもいいが~~リクエストしたときはSQL~~は~~が走らないようにしたい．
ただし開発中は不便なので制限なし，本番環境では制限を書けるという実装がベスト．実装方法は検討中．

このissueがcloseするときに達成されていること
- rdr-bridge以外のクライアントが`/room`を叩いてもSQLが走らないようになっている
- 上の変更に伴ってrdr-bridgeのコードも更新されている

**Comment by equal-l2** [comment]
> 叩けてもいいがSQLは走らない

これってどういう動作ですか？

**Comment by h-takeyeah** [comment]
> 叩けてもいいがSQLは走らない

というのは誤解を招く表現でした．正しくは不正なクライアントがリクエストを送ってきても(=叩いてきても)，認可しないことでクエリが実行されないようにする，でした．

**Comment by equal-l2** [comment]
一応聞いておきたいんですが、不正なクライアントによって `/room` APIを叩かれることによるリスクはどのようなものがありますか？

おそらく研究室の外からのアクセスによるリスクでしょうか。
(研究室にシステムの構成要素が全て物理的に配置される以上、どんな認証方法をとっても研究室に物理的アクセスを持つ者からは理論上rdr-bridgeと同じアクセス方法を取れるので)

**Comment by equal-l2** [comment]
今回の件がそうとは言いませんが、ありもしないリスクに対して無意味な対策をとってしまうのは世の中の常です。
きちんとリスクを分析した上で適切な対策を取るべきです。

**Comment by equal-l2** [comment]
BASIC認証なら実装したことあるので、それでよければ自分が作ります

**Comment by Stroheim001** [comment]
@equal-l2 今回の規模感的にセキュリティがアホみたいに強固で堅牢なものでないといけないとは思いません。

セキュリティ関係は割とまじめに素人なので何とも言えませんが、

---

- ブリッジから通さないこと
- 万が一、不正にやられたとしてもデータのヴァリデーションで弾けること

が確保できていれば十分だと思います。まあ、データのヴァリデーションは最期の砦的な感じのつもりですが、ないよりはましだと思います。(というか製品として出荷するならないほうが問題ではある)

**Comment by Stroheim001** [comment]
どうしてもセキュリティ性を確保したいけど、今はそんな時間がない、ってならIPアドレス付きでログとってれば、localhost以外から来てた奴をピックアップしたらあぶりだせると思いますし、まあ色々手はあると思います。

**Comment by equal-l2** [comment]
現状ブリッジから送ってくるデータが

- ブリッジの読み取りステータス
- 学籍番号

だけなので、validationも大したことできないですね

一応ステータスはすでにvalidateしてるはずです
あと見れるのは学籍番号の桁数とかくらいですかね(教員がどういう番号を持ってるかわからないですが)

**Comment by Stroheim001** [comment]
ぶっちゃけ要件定義そのものに抵触しかねない案件なのでヒアリングで聴く内容にあげておきます

**Comment by equal-l2** [comment]
API周りのアクセスログは普通に取っておいた方がいいですね

**Comment by Stroheim001** [comment]
@equal-l2 せやな～というお気持ち

**Comment by h-takeyeah** [comment]
ヒアリングの結果，認証は必要ないということになりましたのでここでcloseします．必要はなくなりましたが認証機能を実装できる人がいたら，またopenして構いません．
@equal-l2 アクセスログを取る話は別issueでお願いします．
