### ISSUE TITLE
CSVファイルの出力及びその仕様を定める

### ISSUE THREAD

**Issue by Stroheim001** [su-its/ams-backend#75]
本システムの最重要目的は濃厚接触者の有無のトレース、およびそのトレーサビリティの担保である

その方法としてCSVで出力され、それ以降データを加工してPCR検査を促すような動作は我々の管轄外である

しかし、GUIが存在しないという環境が存在する以上、nuxt側からデータをバリデーションして、などという動作を期待することは出来ないため、

CUIだけで必要なCSVファイルを出力しなければならない

---

なお、GUIが存在する場合はバリデーションが入るので、基本的にはどのような形態でも構わないのでデータを出力してくれても問題はないが、可能ならJSONのArrayがnuxt担当者としては楽である。

---

従って、CUI環境下での動作での、インプットされたデータのバリデーション(日付が未来になってないか、出力開始日より出力終了日が未来ではないか等)、そもそも入力値がない場合はエラーとするのか？等検討することは多いので、

よろしくお願いします。

これが終われば、基本的な開発は終了します。

後はITS向けの改良等が存在するだけだと思うので、最後のひと踏ん張り、よろしくお願いします。

**Comment by h-takeyeah** [comment]
@Stroheim001 言葉尻を捉えるようです失礼かもしれないですが，CUIが使えるならモニタがあるということですからNuxtのフロントエンドを使ってもらえばよいのではないですか？

おそらくモニタを繋がずに利用するユーザにCSVデータを提供する方法を考えよう，というのがこのissueの目指すところだと思います．

モニタ無しで利用している場合，一体どのようにCSVデータを提供するとイメージしていたのか，を先生に聞いてみました．曰く，そのときはモニターとキーボード繋いでUSBメモリにコピーする，とのことでした．この使い方であれば，つまりそのときは必ずモニターとキーボードが用意されるということが保証されるのであれば，Nuxtのフロントエンドで用は足りますよね．先生にもそう回答しました．

stkさんが想定しているのは完全にモニタとキーボードが無い環境だと思うのですがどうでしょうか．そういった環境の場合はある程度データがまとまった段階でメールを飛ばすとか，ラズパイに直接モニタを繋いで見るのではなく他の端末からフロントエンドを見られるようにする(現段階でもこれは設定次第でできると思う)などの方法が考えられます．

**Comment by equal-l2** [comment]
どちらのユースケースにしてもバックエンドがCSVを吐くようなエンドポイントは必要かと思います。
(現状だとページネーションとバトルしながらフロントエンドでCSVをコネコネしないといけないので)

---

とりあえずCSVを吐くエンドポイントを作ろうと思うので、以下の要件を決定するのに協力いただきたいです。
- 受け取るクエリ(現状では開始・終了日を示す`since`と`until`だけでいいと思っています)
- エンドポイントのパス(`/access_logs/csv`みたいに掘るか、`/access_logs_csv`みたいに他とフラットにしてしまうか等々……)

**Comment by equal-l2** [comment]
とりあえずのAPIドキュメント的雛形
---
# `/access_logs/csv`

指定された期間のアクセスログをCSVで出力します

## パラメータ
- `since`: 取得する期間の開始日を指定します
- `until`: 取得する期間の終了日を指定します

## 戻り値
以下のようなJSONを返します

```json5
{
  'data': "<CSVデータ>"
}
```

**Comment by h-takeyeah** [comment]
この変更はOKだと思うのですが，単に確認させてください．昨日のヒアリングの時にはおおもとのDBのデータを消す消さないはともかく，Nuxtのフロントエンドを通しては3か月より前には遡れないようにしましょうと決まったと思います．これに対し，下記の仕様の言わんとするところはバックエンド側で3カ月…の制限をかけてしまうということですよね？

> since: 取得する期間の開始日を指定します。デフォルトでは今日から90日(3ヶ月)前の日となります。

昨日はフロントエンドで調整するということになっていたのでバックエンド側は愚直に指定された期間のデータを取ってくる以外は特に何もしない(例えば半年前を指定されたらその通りに持ってくる)ようになっていたので，変更するのね？という確認です．

---

要件について

受け取るクエリは期間だけでいいと思います．

エンドポイントはリソースベースがいいので，リソースそのものではなくリソースの表現形式をリクエスト側が指定できるcsvとかjsonとかつけるのはあまり気持ちのいいものではないです．ですが仕方ないかなあとも思っています．そんな感じなので掘った方が良いのかフラットにしたらいいのかについて何もアイデアがありません．いちおう参考資料 https://qiita.com/uich/items/8d6893e301f817d1390a

返すデータについては実験してみて決める必要があると思います．というかスタンダードがあるのか分からない

バックエンドからのCSVの渡し方について https://qiita.com/ksh-fthr/items/29db7c5c7268ee1802c5 ではバックエンドから返すのはCSVファイルそのものではなく，CSVの**中身**と**ファイル名**(は決め打ちでもいいので無くてもいいかな)のみで，実際にCSVファイルの形にするのはフロントエンド側という実装でした．迷ったらとりあえずこれで進めてみるのはどうでしょうか．

**Comment by Stroheim001** [comment]
@equal-l2 @h-takeyeah デフォ値を3カ月には変えようとは思ってました。
あらかわさんが作って頂いたモックアップのような期限が定まってないものは3カ月にしようとは思ってましたが、私は常に共通処理としてqueryを出すべきですか？
それはそれで仕様変更に強いしITS向けとしては良い品になると思いますが、私の作業が変わるので、どっちなのか決めておいて欲しいです。
それとcsv入りJSONで帰ってくるのか、JSONで帰ってきた奴をcsv化する変換が必要なのか、は早めに回答欲しいです。

最後になりますが、遊橋先生の口ぶり的にむしろ、期間を決めてダウンロードする方がメインにきてほしい感じだったので、タブを逆にしようと思います。構いませんか？

**Comment by equal-l2** [comment]
@h-takeyeah 
>下記の仕様の言わんとするところはバックエンド側で3カ月…の制限をかけてしまうということですよね？

パラメータの「デフォルト」と言っているように、クエリが渡されなかった場合のデフォルトです。
したがってクエリを渡せば「バックエンド側は愚直に指定された期間のデータを取ってくる」ことになります。

>バックエンドからのCSVの渡し方について

自分としてはバックエンドでファイルを生成するエンドポイントを作っておけば、フロントエンドはそこに(適切なクエリパラメータを付与して)リダイレクトしてダウンロード処理ができるようになるので楽かなと思った次第です。
(実際にフロントエンドがそういう動きをできるかは分かりませんが)
この場合、バックエンドは(JSONに包まれていない)生のCSVをそのまま送ることになります。

@Stroheim001 
>私は常に共通処理としてqueryを出すべきですか？

ここ、どういうことでしょうか。詳しく教えてください。

**Comment by h-takeyeah** [comment]
@equal-l2 デフォルトはあくまでデフォルトですね．了解しました

**Comment by equal-l2** [comment]
機能の議論で得られたAPI決定版

---
# `/access_logs/bulk`

指定された期間のアクセスログを、ページネーションなしで返します。

## パラメータ
以下のパラメータはクエリパラメータによって渡すことができます。
- `since`: 取得する期間の開始日を指定します。デフォルトでは今日から90日(3ヶ月)前の日となります。
- `until`: 取得する期間の終了日を指定します。デフォルトでは今日となります。

## 戻り値
以下のようなJSONを返します

```json5
{
  'data': [
    // 該当期間のLogs
  ]
}
```

**Comment by Stroheim001** [comment]
@equal-l2  
> > 私は常に共通処理としてqueryを出すべきですか？
> 
> ここ、どういうことでしょうか。詳しく教えてください。

すみません、体調が良くなくて寝込んでました！！
言いたかったこととしては、デフォ値(3カ月前と今日)を常に出し続けるべきか、という意味でした。

そういう実装は今回ないっぽい感じなので解決してます、ごめんなさい！！
