### ISSUE TITLE
アプリ自体のロジックには関わらないものをまとめるフォルダが無い

### ISSUE THREAD

**Issue by h-takeyeah** [su-its/ams-backend#82]
自分はルートフォルダにはエントリポイント以外のtsはない方がいいと思います。
今後こういう「アプリ自体のロジックには関わらないもの」が追加される時のことを考えると、`app`以下に`utils`とか`misc`みたいなフォルダを掘ってそこに入れておくと良いかもしれません。

_Originally posted by @equal-l2 in https://github.com/su-its/ams-backend/pull/79#discussion_r600004049_

**Comment by h-takeyeah** [comment]
流れとしてはこんな感じ

1. 設定ファイルをyamlにしたのでconfig.tsが設定ファイルとしての意味を持たなくなった
2. config.tsは設定ファイルを読み込んでバリデーションすることに専念してもらう
3. ルートに置いてあると邪魔
4. どこにおけばいいんだ？
5. それ用のフォルダを作ろう

今のところそのフォルダにはconfig.tsを入れたいという需要しかないので，こんな感じをイメージしています．
```
app/
  controllers/
  database/
  models/
  routes/
  <新フォルダ>/
    config.ts
```

**Comment by h-takeyeah** [comment]
名称の候補は`util`，`misc`，`config`あたりでしょうか

**Comment by h-takeyeah** [comment]
新フォルダを`app/`に配置したのはアプリ自体のロジックには関わらないとはいえ，`app/`以下の既存のファイルからしか参照されないフォルダだと認識しているためです．もし本当に全く関係のないファイルを置きたい，というニーズがあったらちょっと考えます

**Comment by Stroheim001** [comment]
@h-takeyeah 
割と冗談抜きでローンチ直前にリファクタリングするのやめてください、責任取れるなら構いせんけど...

気持ちは分からんくもないのですが、今まで動いてたのは確証があるのです。ディレクトリとは言えそれなりに改修加えて可読性上げましたって言われても、喜ぶのは開発者であって、エンドユーザではないんです。

教授がめちゃｸｿできるPJならその方が良いんですが、教授が払った1万円というコストを無視あるいは責任取れるなら、ご自由にやればよいと思います。

まあ、所詮学生のやった戯言、で済ませてもらえるならそもそもこれ以上私関わりたくないんですけどね...
(双極性障害がかなり悪化してて手が震えてる)
