### ISSUE TITLE
リリース

### ISSUE THREAD

**Issue by equal-l2** [su-its/ams-backend#92]
1. 未済タスクがないか確認
2. すべて済んでいるならバージョンをバンプ
3. mainブランチにマージ

**Comment by h-takeyeah** [comment]
ncuして依存パッケージのバージョンをなるべく最新にする作業は必要でしょうか？

**Comment by equal-l2** [comment]
今見てみたらeslintだけ新しいバージョンが出てましたが、実動には影響ないのでそのままで良さそうです。

**Comment by h-takeyeah** [comment]
自分の未済タスクは無いです．バンプするとバージョンはいくつになるんですか？

(いくつだからどうこうという意味ではなく単純に知らないので)

**Comment by equal-l2** [comment]
前回のリリースから破壊的変化(少なくとも設定ファイルの形式変更)があるのでメジャーバージョンを上げちゃいましょう。
PRを出します。

**Comment by equal-l2** [comment]
しました。
