### ISSUE TITLE
同一ユーザが高速で入退室すると壊れる

### ISSUE THREAD

**Issue by equal-l2** [su-its/ams-backend#94]
スクリプトなどで同一ユーザが高速で入退室すると、そのユーザが二度と退室できなくなることがある。

具体的には、以下のような状況：
1. あるユーザが同一時刻に入室&退室し、さらにその時刻内にもう一度入室する
2. `access_logs`テーブルはユーザIDと入室時刻で制約をかけているので、このユーザの退室処理ができなくなる。

通常は入退室処理自体に1秒以上かかる(入退室時に音を鳴らす処理がブロッキングなため)ので、実運用上の問題はおそらくない。

**Comment by h-takeyeah** [comment]
ありがとうございます。解決策としてはユニークなIDを各レコードに振ることでしょうか。

レコードにユニークなIDを振る方法として自分はAUTO INCREMENTしか知らなかったのですが、Maria DBだとSEQUENCEというものも使えるらしくこちらはAUTO INCREMENTに比べて性能面でアドバンテージがあるとかないとか。[参考](https://blog.s-style.co.jp/2018/09/2467/)
